export const escapeHtml = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string))

export function generatePDFFromHTML(html: string, filename: string): void {
  const printWindow = window.open('', '', 'height=600,width=800')
  if (!printWindow) {
    console.error('Failed to open print window')
    return
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${escapeHtml(filename)}</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
          padding: 20px;
          color: #1a1a1a;
          background: white;
        }
        h1 {
          font-size: 24px;
          margin-bottom: 10px;
          font-weight: 700;
        }
        .subtitle {
          font-size: 14px;
          color: #666;
          margin-bottom: 20px;
        }
        .timestamp {
          font-size: 12px;
          color: #999;
          margin-bottom: 20px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20px;
        }
        th {
          background-color: #f5f5f5;
          padding: 12px;
          text-align: left;
          font-weight: 600;
          font-size: 13px;
          border-bottom: 2px solid #ddd;
        }
        td {
          padding: 12px;
          border-bottom: 1px solid #eee;
          font-size: 13px;
        }
        tr:last-child td {
          border-bottom: none;
        }
        .summary {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
          gap: 20px;
          margin-bottom: 30px;
        }
        .summary-item {
          padding: 15px;
          background-color: #f9f9f9;
          border-radius: 4px;
          border-left: 4px solid #3b82f6;
        }
        .summary-label {
          font-size: 12px;
          color: #666;
          font-weight: 500;
          margin-bottom: 5px;
        }
        .summary-value {
          font-size: 20px;
          font-weight: 700;
          color: #1a1a1a;
        }
        .positive {
          color: #10b981;
        }
        .negative {
          color: #ef4444;
        }
        @media print {
          body {
            padding: 0;
          }
          .no-print {
            display: none;
          }
          table {
            page-break-inside: avoid;
          }
          tr {
            page-break-inside: avoid;
          }
        }
      </style>
    </head>
    <body>
      ${html}
      <div class="no-print" style="margin-top: 40px; text-align: center; color: #999; font-size: 12px;">
        <p>Generated by FinPath - Personal Finance Tracker</p>
      </div>
    </body>
    </html>
  `)
  printWindow.document.close()

  setTimeout(() => {
    printWindow.print()
  }, 250)
}

export function downloadPDF(html: string, filename: string): void {
  // Create a hidden div with the content
  const tempDiv = document.createElement('div')
  tempDiv.innerHTML = html
  tempDiv.style.display = 'none'
  document.body.appendChild(tempDiv)

  // Try to use html2pdf if available (fallback graceful if not)
  try {
    generatePDFFromHTML(html, filename)
  } catch (err) {
    console.error('PDF generation failed:', err)
    generatePDFFromHTML(html, filename)
  }

  setTimeout(() => {
    document.body.removeChild(tempDiv)
  }, 1000)
}

export function generateReportHTML(title: string, subtitle: string, summary: { label: string; value: string; variant?: 'positive' | 'negative' }[], tableHTML: string): string {
  const now = new Date()
  const timestamp = now.toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })

  return `
    <h1>${escapeHtml(title)}</h1>
    <p class="subtitle">${escapeHtml(subtitle)}</p>
    <p class="timestamp">Generated on ${timestamp}</p>

    ${summary.length > 0 ? `
      <div class="summary">
        ${summary.map(item => `
          <div class="summary-item">
            <div class="summary-label">${escapeHtml(item.label)}</div>
            <div class="summary-value ${item.variant === 'positive' ? 'positive' : item.variant === 'negative' ? 'negative' : ''}">
              ${escapeHtml(item.value)}
            </div>
          </div>
        `).join('')}
      </div>
    ` : ''}

    ${tableHTML}
  `
}
